### PR TITLE
Issue#271 rework

### PR DESCRIPTION
**Pull request by charlie0605**
Fix duplication issue when accessing two stage at the same time

@helenvarley are those steps you did to get the duplication to happen?

### CODE REVIEW

**Comment by charlie0605** [comment]
@alexanderglenn your not testing what this PR is required to pass, this PR is fixing the issue when player opens two tabs at once, first tab is stage1 and contains only one avatar1, second tab is stage2 containing 2 avatars, avatar1 and avatar2. When the player is on the first tab and puts avatar1 down and then goes to second tab, then puts avatar2 down. When the player goes back to the first tab both avatar will show even though avatar2 is not assigned to the first stage(first tab). Please refer to Helens last comment on this issue.

**Comment by rohrlach** [comment]
Actually - to test this properly, you need to have both stage1 and stage2 open in separate tabs at the same time and watch whether placing an avatar on stage1 sends the update to your (still open) stage2

I'm not convinced the code changes actually address the issue, but so long as you've tested properly I'll trust it.

**Comment by rohrlach** [comment]
@thongteav can you please review again?

**Comment by thongteav** [comment]
@rohrlach I've done the review on the new bug described by Helen.

**Pull request merged**
