### PR TITLE
Issue #322

### PR DESCRIPTION
**Pull request by alexanderglenn**
On the stage, when the user is in the drawing tab and mouses over the canvas; the mouse cursor will change to a pencil icon (24x24) (http://www.iconarchive.com/show/outline-icons-by-iconsmind/Pencil-icon.html). This icon seemed like the least distracting to the user.
When the avatar tab is selected, the mouse cursor changes to the 'grab' icon.
The sound and backdrop tabs have been set to 'auto'. This should keep the standard pointer icon for the mouse cursor when the sound or backdrop tabs have been selected and the user mouses over the canvas.
Note: There are no screenshots as I was not able to capture the mouse cursor in the screenshot.

### CODE REVIEW

**Comment by helenvarley** [comment]
it's a bit hard to review this without being able to test it in action.

**Comment by alexanderglenn** [comment]
The pencil icon will not appear when using the drawing tab in Microsoft Edge. It uses the cross-hair fallback option instead.
The pencil icon works as it should with Firefox and Chrome.

**Comment by alexanderglenn** [comment]
I have removed the two PNG files in assests/images as they were not needed.

**Comment by alexanderglenn** [comment]
The .cur pencil icon used in Edge is different to the .png pencil image used in firefox and Chrome. The images are similar though.

**Comment by alexanderglenn** [comment]
The .png pencil icon has been removed. Chrome, Edge, Firefox and Safari all use the same pencil icon when the drawing tab has been selected.

**Comment by rohrlach** [comment]
Waiting on @thongteav to approve/reject

**Pull request merged**
