### PR TITLE
Issue #273

### PR DESCRIPTION
**Pull request by thongteav**
- **The avatar that has just been placed to the canvas will show both name and image to players and audience without placing it again.**
Player View
image
Audience View
image
Player View
image
Audience View
image

- **The audience will have the avatar removed from their screen when a player drops the avatar.**
Player view
image
Audience view
image
Player view
image
Audience view
image

### CODE REVIEW

**Comment by rohrlach** [comment]
@thongteav is this a fix for the bug described in #273 ?

If so, I'm happy for this to head out with R3-2018 provided it gets at least one approval from another team member.

NOTE: They'll need to actually checkout out the branch and validate that the fix WORKS.

**Comment by thongteav** [comment]
Yes it is to fix issue #273.

**Comment by rohrlach** [comment]
Nice. Send a message to your team mates. See if they can review ASAP

**Comment by vickis** [comment]
great :)

**Comment by rohrlach** [comment]
@charlie0605 issue #273 specifically relates to the Edge browser

**Comment by charlie0605** [comment]
@rohrlach Yes, Edge works find too

**Pull request merged**
