### PR TITLE
R4-2017

### PR DESCRIPTION
**Pull request by rohrlach**
Final release for the year.

Post sprint 12

### CODE REVIEW

**Comment by helenvarley** [comment]
should we be checking this on https://limelight-qa.upstage.org.nz/? it's not accessible to me ..

**Comment by rohrlach** [comment]
Looking into it  now - Believe I see the problem

**Comment by rohrlach** [comment]
QA server is fixed.

**Comment by helenvarley** [comment]
great work, team :) obviously not all of these issues are closed, & many of them spawn other issues in the process ... you will probably have realised by now that that's how it goes! ;) but lots of progress is being made, which is great! :) :+1:

**Pull request merged**
