### PR TITLE
Issue#230

### PR DESCRIPTION
**Pull request by francis-villaflor**
For each stage in the Stages page, 'Enter' and 'Edit' buttons are now only shown. 'Delete' button for deleting a specific stage is now only available when you are in the Edit page for that specific stage. Tested on Chrome and Firefox locally in my Oracle VM. Needs further approval.

Edit - 12:00PM Wednesday 9th May (09/05/18)
I have tested this on Microsoft Edge on Windows through port forwarding via Oracle VM. This works as intended.

### CODE REVIEW

**Comment by vickis** [comment]
separated  - with space between please! :)

**Comment by charlie0605** [comment]
@rohrlach the button is currently separated

**Comment by charlie0605** [comment]
@rohrlach I believe the code that you are talking about refers to the list of stages:
image

The button that we were discussing about is when you edit a specific stage.
image

unless @helenvarley @vickis would also like to change the stage list's button to be separate then we could do that.

**Comment by rohrlach** [comment]
@helenvarley & @vickis can you confirm this?

**Comment by helenvarley** [comment]
i would go for consistency ... if the buttons are separated in one place then they should be separated everywhere (unless there's an argument to have them joined together).

**Comment by vickis** [comment]
agreed
separating them also decreases the opportunity for error

**Comment by rohrlach** [comment]
@charlie0605 please go ahead and make the change.

**Comment by francis-villaflor** [comment]
Stages page buttons separation - Chrome, Firefox, Edge
stages buttons chrome
stages buttons edge
stages buttons firefox


Stage page buttons separation - Chrome, Firefox, Edge
stage buttons chrome
stage buttons edge
stage buttons firefox


Users page buttons separation - Chrome, Firefox, Edge
users buttons chrome
users buttons edge
users buttons firefox


User page buttons separation - Chrome, Firefox, Edge
user buttons chrome
user buttons edge
user buttons firefox

**Pull request merged**
