### PR TITLE
R5-2018

### PR DESCRIPTION
**Pull request by rohrlach**
Contains:
- #205 
- #210 
- #254 
- #312 
- #315

### CODE REVIEW

**Comment by rohrlach** [comment]
Reviewers: Please ensure all Issues mentioned are closed.

**Comment by vickis** [comment]
Approved

**Comment by vickis** [comment]
ok i have the penultimate event for the river project tomorrow
and on tuesdsy at 6am i will be rushing to the airport for a week of
interviews with scientists around the motu for the next project

my window at the moment is april 18 afternoon on ....
i would be happy to meet anytime after that

in between now and then a possible gap would be early thursday 12...
arohamai
vicki :)

**Comment by rohrlach** [comment]
No worries - We'll discuss the arrangement next time we meet.

**Comment by helenvarley** [comment]
i also have pretty limited availability until the end of the month. neither of the two options vicki has suggested above would work for me, sorry!

**Pull request merged**
