### PR TITLE
Issue #115

### PR DESCRIPTION
**Pull request by rohrlach**
This removes the show page for both Avatars and Sounds - Instead opting to go directly to the edit page.  I've left the Stage show page in place as I believe it may still be useful

### CODE REVIEW

**Comment by helenvarley** [comment]
how is the stages Show page useful?
at the moment there are 2 pages: 
- clicking on the name of the stage brings you to a screen where you can add/delete tags and media
- clicking on the "edit" button brings you to a page where you can add/delete tags & change the name of the stage
it seems strange not to be able to do all of these things on the same screen, from either link.

**Comment by rohrlach** [comment]
Because there will (eventually) be more information on it - when you consider Avatar, Audio, Props, backdrops etc.

**Comment by helenvarley** [comment]
won't that information also be on the stage edit screen?

**Comment by rohrlach** [comment]
It might be.

I'm considering a slightly different approach for stages because they're the meeting point for everything, I might drop the Stage edit screen and update the stage name via a popup dialog

**Pull request merged**
