### PR TITLE
R3-2018

### PR DESCRIPTION
**Pull request by rohrlach**
Contains:
- #138
- #273 
- #275

### CODE REVIEW

**Comment by helenvarley** [comment]
not quite sure what i'm meant to be reviewing here - am i qualified to review it??

**Comment by rohrlach** [comment]
@helenvarley essentially you're confirming that the issues mentioned herein are closed and ready for release.

**Comment by rohrlach** [comment]
@helenvarley & @vickis 

I think I'm going to change how these work.  PRs labelled 'release' will simply need an approval from each of you.

The team and I have already vetted the code at this point.

**Comment by helenvarley** [comment]
sounds good paul :)

**Comment by vickis** [comment]
approved paul :)

**Comment by rohrlach** [comment]
@vickis cool. Could you submit an approval through the review system?

**Pull request merged**
