### PR TITLE
Issue #323

### PR DESCRIPTION
**Pull request by MaxButchart**
The Avatar tab is now the default tab when entering a stage and other tabs have been arranged in alphabetical order.

### CODE REVIEW

**Comment by vickis** [comment]
woop woop :)

**Comment by helenvarley** [comment]
should we be seeing this now on https://limelight-qa.upstage.org.nz ? i'm not ...

**Comment by charlie0605** [comment]
No you shouldn’t be able to see it yet

**Comment by thongteav** [comment]
@helenvarley only when this is closed and merged :)

**Comment by rohrlach** [comment]
Looks good to me.

FYI - Please use "Issue #..." As the title of a PR

**Pull request merged**
