### PR TITLE
Issue #202

### PR DESCRIPTION
**Pull request by charlie0605**
Players are able to clear all unheld avatars
- minor bug fix, when player drops avatar, the avatar button title is the avatar name where as previous the title is undefined

### CODE REVIEW

**Comment by rohrlach** [comment]
I'm deliberately delaying this because I think the issue is ill-considered.  I'll need to discuss with @helenvarley and @vickis  next time we meet.

**Comment by helenvarley** [comment]
i don't really understand the minor bug fix description; but being able to clear unheld avatars is quite an important function.

**Comment by rohrlach** [comment]
It is, yes - But I think we've actually not been clear on the acceptance criteria :wink:

**Comment by rohrlach** [comment]
Accepting this for now - If it needs to be changed later, so be it.

**Pull request merged**
